version: 2.1

orbs:
    aws-ecr: circleci/aws-ecr@6.15.2

jobs:
  build_and_test_http_gateway:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/http_gateway
    steps:
      - checkout
      - restore_cache:
          key: http_gateway-{{ checksum "./http_gateway/go.sum" }}
      - run:
          name: http_gateway test
          command: |
            cd ./http_gateway
            go test ./...
      - run:
          name: http_gateway build
          command: |
            cd ./http_gateway
            go build ./...
      - save_cache:
          key: http_gateway-{{ checksum "./http_gateway/go.sum" }}
          paths:
            - /go/pkg/mod

workflows:
  build_test_push:
    jobs:
      - build_and_test_http_gateway
      - aws-ecr/build-and-push-image:
            requires:
                - build_and_test_http_gateway
            region: "${AWS_DEFAULT_REGION}"
            account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
            repo: "${AWS_RESOURCE_NAME_PREFIX}"
            tag: "${CIRCLE_SHA1}"
