version: 2.1

orbs:
  go: circleci/go@1.5.0
  aws-ecr: circleci/aws-ecr@6.15.2

jobs:
  build_and_test_http_gateway:
    executor:
      name: go/default
      tag: "1.13"
    working_directory: ./http_gateway
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test

workflows:
  build_test_push:
    jobs:
      - build_and_test_http_gateway
      - aws-ecr/build-and-push-image:
          requires:
              - build_and_test_http_gateway
          region: AWS_DEFAULT_REGION
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          repo: ${AWS_RESOURCE_NAME_PREFIX}
          tag: "${CIRCLE_SHA1}"
          path: ./http_gateway
