version: 2
jobs:
  build_and_test_http_gateway:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/http_gateway
    steps:
      - checkout
      - restore_cache:
          key: http_gateway-{{ checksum "./http_gateway/go.sum" }}
      - run:
          name: http_gateway test
          command: |
            cd ./http_gateway
            go test ./...
      - run:
          name: http_gateway build
          command: |
            cd ./http_gateway
            go build ./...
      - save_cache:
          key: http_gateway-{{ checksum "./http_gateway/go.sum" }}
          paths:
            - /go/pkg/mod

  build_and_test_communication:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/communication
    steps:
      - checkout
      - restore_cache:
          key: communication-{{ checksum "./communication/pom.xml" }}
      - run:
          name: communication dependency
          command: |
            cd ./communication
            mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: communication-{{ checksum "./communication/pom.xml" }}
      - run:
          name: communication protoc
          command: |
            mkdir -p ./communication/src/main/proto
            cd ./skysign-proto
            make cp_communication
      - run:
          name: communication test
          command: |
            cd ./communication
            mvn test
      - run:
          name: communication compile
          command: |
            cd ./communication
            mvn compile

  build_and_test_client:
    docker:
      - image: circleci/node
    working_directory: ~/client
    steps:
      - checkout
      - run:
          name: client env
          command: |
            cd ./client
            echo REACT_APP_CESIUM_KEY=$CESIUM_KEY > ./.env
      - restore_cache:
          key: client-{{ checksum "./client/package.json" }}
      - run:
          name: client dependency
          command: |
            cd ./client
            npm install
      - save_cache:
          paths:
            - ~/.m2
          key: client-{{ checksum "./client/package.json" }}
      - run:
          name: client test
          command: |
            cd ./client
            npm test
      - run:
          name: client compile
          command: |
            cd ./client
            npm build

  build_and_test_edge:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/edge
    steps:
      - checkout
      - restore_cache:
          key: edge-{{ checksum "./edge/go.sum" }}
      - run:
          name: edge test
          command: |
            cd ./edge
            go test ./...
      - run:
          name: edge build
          command: |
            cd ./edge
            go build ./...
      - save_cache:
          key: edge-{{ checksum "./edge/go.sum" }}
          paths:
            - /go/pkg/mod

  containerize_and_push:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: 
          name: Setup Google Cloud SDK
          command: |
            apt-get install -qq -y gettext
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - setup_remote_docker
      - run: 
          name: protoc
          command: |
            mkdir -p ./communication/src/main/proto
            cd ./skysign-proto
            make cp_communication
      - run: 
          name: http_gateway Docker build and push
          command: |
            cd ./http_gateway
            docker build -t http_gateway .
            docker tag http_gateway gcr.io/$GOOGLE_PROJECT_ID/http_gateway:${CIRCLE_SHA1}
            gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
            docker push gcr.io/$GOOGLE_PROJECT_ID/http_gateway:${CIRCLE_SHA1}
      - run: 
          name: communication Docker build and push
          command: |
            cd ./communication
            docker build -t communication .
            docker tag communication gcr.io/$GOOGLE_PROJECT_ID/communication:${CIRCLE_SHA1}
            gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
            docker push gcr.io/$GOOGLE_PROJECT_ID/communication:${CIRCLE_SHA1}
      - run: 
          name: client Docker build and push
          command: |
            cd ./client
            echo REACT_APP_CESIUM_KEY=$CESIUM_KEY > ./.env
            docker build -t client .
            docker tag client gcr.io/$GOOGLE_PROJECT_ID/client:${CIRCLE_SHA1}
            gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
            docker push gcr.io/$GOOGLE_PROJECT_ID/client:${CIRCLE_SHA1}

workflows:
  version: 2
  build_test_push:
    jobs:
      - build_and_test_http_gateway
      - build_and_test_communication
      - build_and_test_client
      - build_and_test_edge
      - containerize_and_push:
          requires:
            - build_and_test_http_gateway
            - build_and_test_communication
            - build_and_test_client
            - build_and_test_edge
