version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.2
  slack: circleci/slack@3.4.2

slack-fail-post-step: &slack-fail-post-step
  post-steps:
    - slack/status:
          webhook: "${SLACK_WEBHOOK}"
          fail_only: true

jobs:
  build_and_test_http_gateway:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - restore_cache:
          key: http_gateway-{{ checksum "./http_gateway/go.sum" }}
      - run:
          name: http_gateway test
          command: |
            cd ./http_gateway
            go test ./...
      - run:
          name: http_gateway build
          command: |
            cd ./http_gateway
            go build ./...
      - save_cache:
          key: http_gateway-{{ checksum "./http_gateway/go.sum" }}
          paths:
            - /go/pkg/mod

  build_and_test_helper_api:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - restore_cache:
          key: helper-api-{{ checksum "./helper-api/go.sum" }}
      - run:
          name: helper-api test
          command: |
            cd ./helper-api
            go test ./...
      - run:
          name: helper-api build
          command: |
            cd ./helper-api
            go build ./...
      - save_cache:
          key: helper-api-{{ checksum "./helper-api/go.sum" }}
          paths:
            - /go/pkg/mod

  build_and_test_communication:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/communication
    steps:
      - checkout
      - restore_cache:
          key: communication-{{ checksum "./communication/pom.xml" }}
      - run:
          name: communication dependency
          command: |
            cd ./communication
            mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: communication-{{ checksum "./communication/pom.xml" }}
      - run:
          name: communication test
          command: |
            cd ./communication
            mvn test
      - run:
          name: communication compile
          command: |
            cd ./communication
            mvn compile

  build_and_test_mission:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/mission
    steps:
      - checkout
      - restore_cache:
          key: mission-{{ checksum "./mission/pom.xml" }}
      - run:
          name: mission dependency
          command: |
            cd ./mission
            mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: mission-{{ checksum "./mission/pom.xml" }}
      - run:
          name: mission test
          command: |
            cd ./mission
            mvn test
      - run:
          name: mission compile
          command: |
            cd ./mission
            mvn compile

  build_and_test_client:
    docker:
      - image: circleci/node
    working_directory: ~/client
    steps:
      - checkout
      - run:
          name: client env
          command: |
            cd ./client
            echo REACT_APP_CESIUM_KEY=${CESIUM_KEY} > ./.env
      - restore_cache:
          key: client-{{ checksum "./client/package.json" }}
      - run:
          name: client dependency
          command: |
            cd ./client
            npm install
      - save_cache:
          paths:
            - ~/.m2
          key: client-{{ checksum "./client/package.json" }}
      - run:
          name: client test
          command: |
            cd ./client
            npm test
      - run:
          name: client compile
          command: |
            cd ./client
            npm build

  build_and_test_edge:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/edge
    steps:
      - checkout
      - restore_cache:
          key: edge-{{ checksum "./edge/go.sum" }}
      - run:
          name: edge test
          command: |
            cd ./edge
            go test ./...
      - run:
          name: edge build
          command: |
            cd ./edge
            go build ./...
      - save_cache:
          key: edge-{{ checksum "./edge/go.sum" }}
          paths:
            - /go/pkg/mod

  build_and_push_http_gateway:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          region: AWS_DEFAULT_REGION
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          repo: ${AWS_RESOURCE_NAME_PREFIX}
          tag: "http_gateway_${CIRCLE_SHA1}"
          path: ./http_gateway

  build_and_push_helper_api:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          region: AWS_DEFAULT_REGION
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          repo: ${AWS_RESOURCE_NAME_PREFIX}
          tag: "helper-api_${CIRCLE_SHA1}"
          path: ./helper-api

  build_and_push_communication:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          region: AWS_DEFAULT_REGION
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          repo: ${AWS_RESOURCE_NAME_PREFIX}
          tag: "communication_${CIRCLE_SHA1}"
          path: ./communication

  build_and_push_mission:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          region: AWS_DEFAULT_REGION
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          repo: ${AWS_RESOURCE_NAME_PREFIX}
          tag: "mission_${CIRCLE_SHA1}"
          path: ./mission

  build_and_push_client:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          region: AWS_DEFAULT_REGION
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          repo: ${AWS_RESOURCE_NAME_PREFIX}
          tag: "client_${CIRCLE_SHA1}"
          path: ./client
          extra-build-args: "--build-arg CESIUM_KEY=${CESIUM_KEY}"

  create_pull_request:
    docker:
      - image: circleci/python:3.7.4-stretch
    steps:
      - checkout
      - run:
          name: install hub
          command: |
            curl -sSLf https://github.com/github/hub/releases/download/v2.8.3/hub-linux-amd64-2.8.3.tgz | \
            tar zxf - --strip-components=1 -C /tmp/ && \
            sudo mv /tmp/bin/hub /usr/local/bin/hub
            hub --version
      - run:
          name: install envsubst
          command: |
            sudo apt-get install -qq -y gettext
      - run:
          name: git clone commit push create pull request
          command: |
            git config --global user.name tomofiles-circleci
            git config --global user.email tomofiles-circleci@email.com
            git clone git@github.com:Tomofiles/${SKYSIGN_CONFIG_REPO}.git
            cd ${SKYSIGN_CONFIG_REPO}/
            git checkout -b release-${CIRCLE_SHA1}
            rm -f manifest/*
            envsubst < ../build/deploy/skysign-client.yaml > manifest/skysign-client.yaml
            envsubst < ../build/deploy/skysign-client-backend.yaml > manifest/skysign-client-backend.yaml
            envsubst < ../build/deploy/skysign-communication.yaml > manifest/skysign-communication.yaml
            envsubst < ../build/deploy/skysign-communication-backend.yaml > manifest/skysign-communication-backend.yaml
            envsubst < ../build/deploy/skysign-communication-gateway.yaml > manifest/skysign-communication-gateway.yaml
            envsubst < ../build/deploy/skysign-communication-gateway-backend.yaml > manifest/skysign-communication-gateway-backend.yaml
            envsubst < ../build/deploy/skysign-endpoint.yaml > manifest/skysign-endpoint.yaml
            envsubst < ../build/deploy/skysign-helper.yaml > manifest/skysign-helper.yaml
            envsubst < ../build/deploy/skysign-helper-backend.yaml > manifest/skysign-helper-backend.yaml
            envsubst < ../build/deploy/skysign-helper-gateway.yaml > manifest/skysign-helper-gateway.yaml
            envsubst < ../build/deploy/skysign-helper-gateway-backend.yaml > manifest/skysign-helper-gateway-backend.yaml
            envsubst < ../build/deploy/skysign-mission.yaml > manifest/skysign-mission.yaml
            envsubst < ../build/deploy/skysign-mission-backend.yaml > manifest/skysign-mission-backend.yaml
            envsubst < ../build/deploy/skysign-mission-gateway.yaml > manifest/skysign-mission-gateway.yaml
            envsubst < ../build/deploy/skysign-mission-gateway-backend.yaml > manifest/skysign-mission-gateway-backend.yaml
            envsubst < ../build/deploy/skysign-vehicle-gateway.yaml > manifest/skysign-vehicle-gateway.yaml
            envsubst < ../build/deploy/skysign-vehicle-gateway-backend.yaml > manifest/skysign-vehicle-gateway-backend.yaml
            git add .
            git commit -m "release-${CIRCLE_SHA1}"
            git push --set-upstream origin release-${CIRCLE_SHA1}
            hub pull-request -F .github/PULL_REQUEST_TEMPLATE.md -m "[image update] skysign ${CIRCLE_SHA1}"

  notify-slack:
    docker:
      - image: "cimg/base:stable"
    steps:
      - slack/status:
          webhook: "${SLACK_WEBHOOK}"

workflows:
  skysign-cicd-workflow:
    jobs:
      - build_and_test_http_gateway: *slack-fail-post-step
      - build_and_test_helper_api: *slack-fail-post-step
      - build_and_test_communication: *slack-fail-post-step
      - build_and_test_mission: *slack-fail-post-step
      - build_and_test_client: *slack-fail-post-step
      - build_and_test_edge: *slack-fail-post-step
      - build_and_push_http_gateway:
          requires:
            - build_and_test_http_gateway
          <<: *slack-fail-post-step
      - build_and_push_helper_api:
          requires:
            - build_and_test_helper_api
          <<: *slack-fail-post-step
      - build_and_push_communication:
          requires:
            - build_and_test_communication
          <<: *slack-fail-post-step
      - build_and_push_mission:
          requires:
            - build_and_test_mission
          <<: *slack-fail-post-step
      - build_and_push_client:
          requires:
            - build_and_test_client
          <<: *slack-fail-post-step
      - notify-slack:
          requires:
            - build_and_push_http_gateway
            - build_and_push_helper_api
            - build_and_push_communication
            - build_and_push_mission
            - build_and_push_client
      - create_pull_request:
          requires:
            - notify-slack
          filters:
            branches:
              only: master
