GOPATH := $(shell go env GOPATH)
GOBIN := $(GOPATH)/bin

compile_http_gateway/communication: vehicle.proto communication_user.proto communication_vehicle.proto
	protoc -I/usr/local/include -I.   -I$(GOPATH)/src   -I$(GOPATH)/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.9.6/third_party/googleapis   --go_out=plugins=grpc:../http_gateway/pkg/skysign_proto vehicle.proto
	protoc -I/usr/local/include -I.   -I$(GOPATH)/src   -I$(GOPATH)/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.9.6/third_party/googleapis   --go_out=plugins=grpc:../http_gateway/pkg/skysign_proto communication_user.proto
	protoc -I/usr/local/include -I.   -I$(GOPATH)/src   -I$(GOPATH)/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.9.6/third_party/googleapis   --go_out=plugins=grpc:../http_gateway/pkg/skysign_proto communication_vehicle.proto

compile_gw_http_gateway/communication: vehicle.proto communication_user.proto communication_vehicle.proto
	protoc -I/usr/local/include -I.   -I$(GOPATH)/src   -I$(GOPATH)/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.9.6/third_party/googleapis   --grpc-gateway_out=logtostderr=true,allow_delete_body=true:../http_gateway/pkg/skysign_proto vehicle.proto
	protoc -I/usr/local/include -I.   -I$(GOPATH)/src   -I$(GOPATH)/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.9.6/third_party/googleapis   --grpc-gateway_out=logtostderr=true,allow_delete_body=true:../http_gateway/pkg/skysign_proto communication_user.proto
	protoc -I/usr/local/include -I.   -I$(GOPATH)/src   -I$(GOPATH)/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.9.6/third_party/googleapis   --grpc-gateway_out=logtostderr=true,allow_delete_body=true:../http_gateway/pkg/skysign_proto communication_vehicle.proto

cp_communication: vehicle.proto communication_user.proto communication_vehicle.proto
	cp vehicle.proto ../communication/src/main/proto
	cp communication_user.proto ../communication/src/main/proto
	cp communication_vehicle.proto ../communication/src/main/proto